### ISSUE TITLE
Module not found: Can't resolve 'circle-progress-ts' in 'D:\MyCode\circularprogressbar\src'

### ISSUE THREAD

**Issue by lchandramohan** [marinewater/circle-progress#4]
Hi,

I tried to use your package in sample react-create-app.

After adding the NPM Package, I follow the steps which you mentioned and its throwing error

Module not found: Can't resolve 'circle-progress-ts' in 'D:\MyCode\circularprogressbar\src'

Please help me resolve this problem.

![image](https://user-images.githubusercontent.com/5810177/55782971-f9ffab80-5adf-11e9-9c85-746865735d5c.png)
![image](https://user-images.githubusercontent.com/5810177/55783027-1ac80100-5ae0-11e9-8d23-e6ff52bf91c4.png)

![image](https://user-images.githubusercontent.com/5810177/55783131-54990780-5ae0-11e9-8b7a-27c3abb3d547.png)

**App.js**

import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import {Progress} from 'circle-progress-ts';

class App extends Component {
  constructor(props) {
    super(props);
    // Don't call this.setState() here!
    const circle = document.querySelector( '.circle' );
    const p = new Progress( circle );

    // change progress
    p.progress( 20 );
    p.progress_animate( 60, 500 );
  }
  
  render() {
    return (
      <div className="App">
        <div class="circle"></div>
      </div>
    );
  }
}

export default App;

**Comment by marinewater** [comment]
try to uncomment the progress.min.js script and replace
```javascript
import {Progress} from 'circle-progress-ts';
```
with
```javascript
const { Progress } = progress;
```
